spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isee?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.cv.config.ClassName
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  #邮箱验证配置
  mail:
    username: 17855776325@163.com
    password: UGZPVALOWAXOUWRQ
    host: smtp.163.com
server:
  port: 8181
